/**
 * Generate a minimal valid PDF fixture for E2E tests.
 *
 * Run:
 *   node --experimental-strip-types packages/signer/scripts/gen-test-pdf.ts
 *
 * Output:
 *   apps/pwa/tests/e2e/fixtures/sample.pdf — single-page A4, "firmar.ec sample"
 *
 * @see apps/pwa/tests/e2e/firma.spec.ts
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument, StandardFonts } from 'pdf-lib';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..', '..', '..');
const OUT_DIR = join(REPO_ROOT, 'apps', 'pwa', 'tests', 'e2e', 'fixtures');
const OUT_PATH = join(OUT_DIR, 'sample.pdf');

async function main(): Promise<void> {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  const pdfDoc = await PDFDocument.create();
  pdfDoc.setTitle('firmar.ec — sample');
  pdfDoc.setAuthor('firmar.ec test fixture');
  pdfDoc.setProducer('pdf-lib (gen-test-pdf.ts)');
  pdfDoc.setCreator('firmar.ec E2E');
  pdfDoc.setCreationDate(new Date('2026-01-01T00:00:00Z'));
  pdfDoc.setModificationDate(new Date('2026-01-01T00:00:00Z'));

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  page.drawText('firmar.ec — sample document', {
    x: 60,
    y: 780,
    size: 22,
    font,
  });
  page.drawText('Generated by gen-test-pdf.ts for Playwright E2E tests.', {
    x: 60,
    y: 740,
    size: 12,
    font,
  });
  page.drawText('No real signatures here — synthetic test fixture only.', {
    x: 60,
    y: 720,
    size: 10,
    font,
  });

  const bytes = await pdfDoc.save({ useObjectStreams: false });
  writeFileSync(OUT_PATH, bytes);
  console.log(`[gen-test-pdf] wrote ${OUT_PATH} (${bytes.byteLength} bytes)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
