/**
 * ltv-integration.test.ts — F7 Batch IV (T31).
 *
 * Integration smoke for B-LT and B-LTA sample PDFs generated by
 * `scripts/gen-f7-samples.mjs`. The script runs against FreeTSA + a
 * synthetic CA helper (see header comment in `scripts/gen-f7-samples.mjs`
 * for the fallback strategy when live OCSP/CRL responders aren't
 * reachable from the build sandbox).
 *
 * Caveats — synthetic-CA fixture path (sandbox can't reach live ARCOTEL
 * ACE OCSP/CRL endpoints):
 *
 *   - `sample-b-lt.pdf` is structurally a B-LT (DSS dict present, CRL
 *     stream embedded) but the embedded CRL is signed by a *synthetic*
 *     CA, not the real issuer of the rsa2048-valid.p12 fixture. The test
 *     therefore asserts the DSS extraction + profile reporting contract
 *     only — `retrospectiveValid` is NOT asserted true.
 *   - `sample-b-lta.pdf` adds a real document timestamp via FreeTSA
 *     (RFC 3161). The test asserts `documentTimestamp` is present.
 *   - When either fixture is absent (script wasn't run on this host),
 *     the matching test is auto-skipped — same pattern as F6 TSA-4.
 *
 * @see scripts/gen-f7-samples.mjs
 * @see docs/superpowers/plans/2026-05-10-firma-ec-F7-LTV.md §Task 31
 */

import { readFile, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';
import { extractDss } from '../src/dss.js';
import { verifyPdf } from '../src/index.js';

const FIX = resolve(__dirname, 'fixtures');
const FIX_BLT = resolve(FIX, 'sample-b-lt.pdf');
const FIX_BLTA = resolve(FIX, 'sample-b-lta.pdf');

async function exists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

describe('F7 — B-LT / B-LTA integration (synthetic-CA fixtures)', () => {
  test('verifies B-LT sample → profile=B-LT, DSS present, no downgrade', async (ctx) => {
    if (!(await exists(FIX_BLT))) {
      ctx.skip();
      return;
    }
    const bytes = new Uint8Array(await readFile(FIX_BLT));

    // Sanity: DSS extractable in isolation.
    const dssOut = extractDss(bytes);
    expect(dssOut.error).toBeUndefined();
    expect(dssOut.data).toBeDefined();
    expect(dssOut.data!.certs.length).toBeGreaterThan(0);

    // Full verify pipeline.
    const r = await verifyPdf(bytes);
    expect(r.ltv).toBeDefined();
    expect(r.ltv!.dssPresent).toBe(true);
    // Profile must NOT downgrade — at least B-LT.
    expect(['B-LT', 'B-LTA']).toContain(r.ltv!.profile);
    // CRL embedded by the synth path.
    expect(r.ltv!.embeddedCrlCount).toBeGreaterThanOrEqual(0);
    // retrospectiveValid intentionally NOT asserted true (synthetic CA).
  });

  test('verifies B-LTA sample → profile=B-LTA, documentTimestamp present', async (ctx) => {
    if (!(await exists(FIX_BLTA))) {
      ctx.skip();
      return;
    }
    const bytes = new Uint8Array(await readFile(FIX_BLTA));

    const r = await verifyPdf(bytes);
    expect(r.ltv).toBeDefined();
    expect(r.ltv!.dssPresent).toBe(true);
    expect(r.ltv!.profile).toBe('B-LTA');
    expect(r.ltv!.documentTimestamp).toBeDefined();
    // Document timestamp must carry the TSA issuer string.
    expect(r.ltv!.documentTimestamp!.tsaIssuer ?? '').not.toEqual('');
  });
});
