/**
 * Tests for parsePfx — covers all error paths and the happy paths
 * for RSA-2048, RSA-1024 (weak — accepted at parse, rejected at sign),
 * ECDSA P-256, expired and not-yet-valid certs (accepted at parse).
 *
 * Fixtures generated by:
 *   node --experimental-strip-types packages/signer/scripts/gen-test-p12.ts
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { webcrypto } from 'node:crypto';
import { describe, expect, it, beforeAll } from 'vitest';
import * as pkijs from 'pkijs';
import { parsePfx } from '../src/p12.js';
import { SignerError } from '../src/errors.js';

// pkijs needs an engine wired in Node (no global Crypto/SubtleCrypto by default in older Node;
// Node 20+ has it on `crypto.webcrypto`).
beforeAll(() => {
  pkijs.setEngine(
    'node-webcrypto',
    new pkijs.CryptoEngine({ name: 'node-webcrypto', crypto: webcrypto as unknown as Crypto }),
  );
});

const FIX_DIR = join(__dirname, 'fixtures');
const PIN = 'test1234';

function loadFixture(name: string): Uint8Array {
  const path = join(FIX_DIR, name);
  if (!existsSync(path)) {
    throw new Error(
      `Fixture missing: ${path}\nRun: node --experimental-strip-types packages/signer/scripts/gen-test-p12.ts`,
    );
  }
  return new Uint8Array(readFileSync(path));
}

describe('parsePfx — happy paths', () => {
  it('parses RSA-2048 valid → sigAlg=RSA-PKCS1-SHA256', async () => {
    const pfx = loadFixture('rsa2048-valid.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('RSA-PKCS1-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer RSA-2048');
    expect(result.signingCert.issuerCN).toBe('Test Signer RSA-2048');
    expect(result.signingCert.der.length).toBeGreaterThan(0);
    expect(result.signingCert.serialHex).toMatch(/^[0-9A-F]+$/);
    expect(result.intermediates).toHaveLength(0);
    expect(result.privateKeyJwk.kty).toBe('RSA');
  });

  it('parses RSA-1024 weak → accepted at parse (rejected at sign time)', async () => {
    // Decision: parsePfx is structural; weak-key rejection is a signing-policy concern.
    // This test pins that contract so future changes are deliberate.
    const pfx = loadFixture('rsa1024-weak.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('RSA-PKCS1-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer RSA-1024 (weak)');
  });

  it('parses RSA-2048 3DES legacy (Ecuadorian ECI cipher) → SUCCESS', async () => {
    // P0 regression guard for v0.4.3. ALL real-world Ecuadorian .p12 files
    // (BCE, Security Data, ArgosData, ANFAC, ConsejoJudicatura) are encrypted
    // with `pbeWithSHAAnd3-KeyTripleDES-CBC`. Web Crypto API has no 3DES, so
    // pkijs throws `pfx_unsupported_algo`. node-forge has full coverage.
    const pfx = loadFixture('rsa2048-3des-legacy.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('RSA-PKCS1-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer 3DES Legacy EC');
    expect(result.privateKeyJwk.kty).toBe('RSA');
    // Sanity: PKCS#8 DER is non-empty and starts with SEQUENCE tag (0x30).
    const pkcs8 = (result as unknown as { privateKeyPkcs8Der: ArrayBuffer }).privateKeyPkcs8Der;
    expect(pkcs8.byteLength).toBeGreaterThan(100);
    expect(new Uint8Array(pkcs8)[0]).toBe(0x30);
  });

  it('parses RSA-2048 3DES legacy with WRONG PIN → pin_invalid', async () => {
    const pfx = loadFixture('rsa2048-3des-legacy.p12');
    await expect(parsePfx(pfx, 'wrong-pin')).rejects.toMatchObject({ code: 'pin_invalid' });
  });

  // v0.4.7: ECDSA P-256 fixture re-enabled. p12.ts now extracts bag.asn1 raw
  // (PKCS#8 PrivateKeyInfo) when forge cannot model the EC key, and emits it as DER.
  // Real-world Ecuadorian ECIs are all RSA today; this path covers future ECDSA certs.
  it('parses ECDSA P-256 valid → sigAlg=ECDSA-P256-SHA256', async () => {
    const pfx = loadFixture('ecdsa-p256-valid.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('ECDSA-P256-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer ECDSA');
    expect(result.privateKeyJwk.kty).toBe('EC');
    // Sanity: PKCS#8 DER is non-empty and starts with SEQUENCE tag (0x30).
    const pkcs8 = (result as unknown as { privateKeyPkcs8Der: ArrayBuffer }).privateKeyPkcs8Der;
    expect(pkcs8.byteLength).toBeGreaterThan(50);
    expect(new Uint8Array(pkcs8)[0]).toBe(0x30);
  });

  it('parses expired cert OK (validity is checked at sign time, not parse time)', async () => {
    // Same rationale as RSA-1024: parsePfx is a pure structural parser.
    // Documented in src/p12.ts header.
    const pfx = loadFixture('cert-expired.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.signingCert.notAfter.getTime()).toBeLessThan(Date.now());
  });

  it('parses not-yet-valid cert OK (validity is checked at sign time, not parse time)', async () => {
    const pfx = loadFixture('cert-not-yet-valid.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.signingCert.notBefore.getTime()).toBeGreaterThan(Date.now());
  });
});

describe('parsePfx — error paths', () => {
  it('throws SignerError(pin_invalid) on wrong PIN', async () => {
    const pfx = loadFixture('rsa2048-valid.p12');
    await expect(parsePfx(pfx, 'wrong-pin')).rejects.toBeInstanceOf(SignerError);
    await expect(parsePfx(pfx, 'wrong-pin')).rejects.toMatchObject({ code: 'pin_invalid' });
  });

  it('throws SignerError(pfx_corrupt) on random bytes', async () => {
    const pfx = loadFixture('corrupt.p12');
    await expect(parsePfx(pfx, PIN)).rejects.toBeInstanceOf(SignerError);
    await expect(parsePfx(pfx, PIN)).rejects.toMatchObject({ code: 'pfx_corrupt' });
  });

  it('throws SignerError(pfx_corrupt) on empty input', async () => {
    await expect(parsePfx(new Uint8Array(0), PIN)).rejects.toMatchObject({ code: 'pfx_corrupt' });
  });

  it('throws SignerError(pfx_corrupt) on truncated DER', async () => {
    const pfx = loadFixture('rsa2048-valid.p12');
    const truncated = pfx.slice(0, 50); // chop off most of the structure
    await expect(parsePfx(truncated, PIN)).rejects.toBeInstanceOf(SignerError);
  });
});

describe('SignerError shape', () => {
  it('is an Error subclass with code + name', () => {
    const e = new SignerError('pin_invalid', 'test');
    expect(e).toBeInstanceOf(Error);
    expect(e.name).toBe('SignerError');
    expect(e.code).toBe('pin_invalid');
    expect(e.message).toBe('test');
  });

  it('carries cause when provided', () => {
    const inner = new Error('inner');
    const e = new SignerError('pfx_corrupt', 'wrap', inner);
    expect(e.cause).toBe(inner);
  });
});
