/**
 * Tests for parsePfx — covers all error paths and the happy paths
 * for RSA-2048, RSA-1024 (weak — accepted at parse, rejected at sign),
 * ECDSA P-256, expired and not-yet-valid certs (accepted at parse).
 *
 * Fixtures generated by:
 *   node --experimental-strip-types packages/signer/scripts/gen-test-p12.ts
 */

import { webcrypto } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import forge from 'node-forge';
import * as pkijs from 'pkijs';
import { beforeAll, describe, expect, it } from 'vitest';
import { SignerError } from '../src/errors.js';
import { parsePfx } from '../src/p12.js';

// pkijs needs an engine wired in Node (no global Crypto/SubtleCrypto by default in older Node;
// Node 20+ has it on `crypto.webcrypto`).
beforeAll(() => {
  pkijs.setEngine(
    'node-webcrypto',
    new pkijs.CryptoEngine({ name: 'node-webcrypto', crypto: webcrypto as unknown as Crypto }),
  );
});

const FIX_DIR = join(__dirname, 'fixtures');
const PIN = 'test1234';

function loadFixture(name: string): Uint8Array {
  const path = join(FIX_DIR, name);
  if (!existsSync(path)) {
    throw new Error(
      `Fixture missing: ${path}\nRun: node --experimental-strip-types packages/signer/scripts/gen-test-p12.ts`,
    );
  }
  return new Uint8Array(readFileSync(path));
}

describe('parsePfx — happy paths', () => {
  it('parses RSA-2048 valid → sigAlg=RSA-PKCS1-SHA256', async () => {
    const pfx = loadFixture('rsa2048-valid.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('RSA-PKCS1-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer RSA-2048');
    expect(result.signingCert.issuerCN).toBe('Test Signer RSA-2048');
    expect(result.signingCert.der.length).toBeGreaterThan(0);
    expect(result.signingCert.serialHex).toMatch(/^[0-9A-F]+$/);
    expect(result.intermediates).toHaveLength(0);
    expect(result.privateKeyJwk.kty).toBe('RSA');
  });

  it('parses RSA-1024 weak → accepted at parse (rejected at sign time)', async () => {
    // Decision: parsePfx is structural; weak-key rejection is a signing-policy concern.
    // This test pins that contract so future changes are deliberate.
    const pfx = loadFixture('rsa1024-weak.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('RSA-PKCS1-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer RSA-1024 (weak)');
  });

  it('parses RSA-2048 3DES legacy (Ecuadorian ECI cipher) → SUCCESS', async () => {
    // P0 regression guard for v0.4.3. ALL real-world Ecuadorian .p12 files
    // (BCE, Security Data, ArgosData, ANFAC, ConsejoJudicatura) are encrypted
    // with `pbeWithSHAAnd3-KeyTripleDES-CBC`. Web Crypto API has no 3DES, so
    // pkijs throws `pfx_unsupported_algo`. node-forge has full coverage.
    const pfx = loadFixture('rsa2048-3des-legacy.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('RSA-PKCS1-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer 3DES Legacy EC');
    expect(result.privateKeyJwk.kty).toBe('RSA');
    // Sanity: PKCS#8 DER is non-empty and starts with SEQUENCE tag (0x30).
    const pkcs8 = (result as unknown as { privateKeyPkcs8Der: ArrayBuffer }).privateKeyPkcs8Der;
    expect(pkcs8.byteLength).toBeGreaterThan(100);
    expect(new Uint8Array(pkcs8)[0]).toBe(0x30);
  });

  it('parses RSA-2048 3DES legacy with WRONG PIN → pin_invalid', async () => {
    const pfx = loadFixture('rsa2048-3des-legacy.p12');
    await expect(parsePfx(pfx, 'wrong-pin')).rejects.toMatchObject({ code: 'pin_invalid' });
  });

  // v0.4.7: ECDSA P-256 fixture re-enabled. p12.ts now extracts bag.asn1 raw
  // (PKCS#8 PrivateKeyInfo) when forge cannot model the EC key, and emits it as DER.
  // Real-world Ecuadorian ECIs are all RSA today; this path covers future ECDSA certs.
  it('parses ECDSA P-256 valid → sigAlg=ECDSA-P256-SHA256', async () => {
    const pfx = loadFixture('ecdsa-p256-valid.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.sigAlg).toBe('ECDSA-P256-SHA256');
    expect(result.signingCert.subjectCN).toBe('Test Signer ECDSA');
    expect(result.privateKeyJwk.kty).toBe('EC');
    // Sanity: PKCS#8 DER is non-empty and starts with SEQUENCE tag (0x30).
    const pkcs8 = (result as unknown as { privateKeyPkcs8Der: ArrayBuffer }).privateKeyPkcs8Der;
    expect(pkcs8.byteLength).toBeGreaterThan(50);
    expect(new Uint8Array(pkcs8)[0]).toBe(0x30);
  });

  it('parses expired cert OK (validity is checked at sign time, not parse time)', async () => {
    // Same rationale as RSA-1024: parsePfx is a pure structural parser.
    // Documented in src/p12.ts header.
    const pfx = loadFixture('cert-expired.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.signingCert.notAfter.getTime()).toBeLessThan(Date.now());
  });

  it('parses not-yet-valid cert OK (validity is checked at sign time, not parse time)', async () => {
    const pfx = loadFixture('cert-not-yet-valid.p12');
    const result = await parsePfx(pfx, PIN);
    expect(result.signingCert.notBefore.getTime()).toBeGreaterThan(Date.now());
  });
});

describe('parsePfx — error paths', () => {
  it('throws SignerError(pin_invalid) on wrong PIN', async () => {
    const pfx = loadFixture('rsa2048-valid.p12');
    await expect(parsePfx(pfx, 'wrong-pin')).rejects.toBeInstanceOf(SignerError);
    await expect(parsePfx(pfx, 'wrong-pin')).rejects.toMatchObject({ code: 'pin_invalid' });
  });

  it('throws SignerError(pfx_corrupt) on random bytes', async () => {
    const pfx = loadFixture('corrupt.p12');
    await expect(parsePfx(pfx, PIN)).rejects.toBeInstanceOf(SignerError);
    await expect(parsePfx(pfx, PIN)).rejects.toMatchObject({ code: 'pfx_corrupt' });
  });

  it('throws SignerError(pfx_corrupt) on empty input', async () => {
    await expect(parsePfx(new Uint8Array(0), PIN)).rejects.toMatchObject({ code: 'pfx_corrupt' });
  });

  it('throws SignerError(pfx_corrupt) on truncated DER', async () => {
    const pfx = loadFixture('rsa2048-valid.p12');
    const truncated = pfx.slice(0, 50); // chop off most of the structure
    await expect(parsePfx(truncated, PIN)).rejects.toBeInstanceOf(SignerError);
  });
});

describe('parsePfx — PIN whitespace recovery (mobile keyboard mangling)', () => {
  // Builds a 3DES-legacy .p12 in-memory (Ecuadorian ECI shape) with a password
  // containing a `+` — the exact failure reported on Samsung (2026-05-21). A
  // forge round-trip confirms the `+` itself is fine; the real-world failure is
  // the on-screen keyboard inserting a space around the symbol key. parsePfx
  // tries trimmed + whitespace-stripped candidates AFTER the as-typed PIN.
  const REAL_PIN = 'clave+2026';
  let plusPfx: Uint8Array;

  beforeAll(() => {
    const keys = forge.pki.rsa.generateKeyPair(1024);
    const cert = forge.pki.createCertificate();
    cert.publicKey = keys.publicKey;
    cert.serialNumber = '01';
    cert.validity.notBefore = new Date();
    cert.validity.notAfter = new Date(Date.now() + 86_400_000);
    const attrs = [{ name: 'commonName', value: 'Test Plus PIN' }];
    cert.setSubject(attrs);
    cert.setIssuer(attrs);
    cert.sign(keys.privateKey);
    const asn1 = forge.pkcs12.toPkcs12Asn1(keys.privateKey, [cert], REAL_PIN, {
      algorithm: '3des',
    });
    const der = forge.asn1.toDer(asn1).getBytes();
    const out = new Uint8Array(der.length);
    for (let i = 0; i < der.length; i++) out[i] = der.charCodeAt(i) & 0xff;
    plusPfx = out;
  });

  it('parses with the exact `+` PIN', async () => {
    const result = await parsePfx(plusPfx, REAL_PIN);
    expect(result.signingCert.subjectCN).toBe('Test Plus PIN');
  });

  it('recovers when keyboard adds spaces AROUND the `+` (inner space)', async () => {
    // `clave + 2026` — trim() cannot fix this; whitespace-strip candidate does.
    const result = await parsePfx(plusPfx, 'clave + 2026');
    expect(result.signingCert.subjectCN).toBe('Test Plus PIN');
  });

  it('recovers a trailing space (trim candidate)', async () => {
    const result = await parsePfx(plusPfx, `${REAL_PIN} `);
    expect(result.signingCert.subjectCN).toBe('Test Plus PIN');
  });

  it('still rejects a genuinely wrong PIN (no false-accept from candidates)', async () => {
    await expect(parsePfx(plusPfx, 'otra-clave-9999')).rejects.toMatchObject({
      code: 'pin_invalid',
    });
  });
});

describe('SignerError shape', () => {
  it('is an Error subclass with code + name', () => {
    const e = new SignerError('pin_invalid', 'test');
    expect(e).toBeInstanceOf(Error);
    expect(e.name).toBe('SignerError');
    expect(e.code).toBe('pin_invalid');
    expect(e.message).toBe('test');
  });

  it('carries cause when provided', () => {
    const inner = new Error('inner');
    const e = new SignerError('pfx_corrupt', 'wrap', inner);
    expect(e.cause).toBe(inner);
  });
});
